spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tcellcrm
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
