spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: eureka
            uri: http://localhost:8888
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/
          - id: eureka-static
            uri: http://localhost:8888
            predicates:
              - Path=/eureka/**
          - id: authserver
            uri: lb://authserver
            predicates:
              - Path=/api/v1/auth/**
          - id: customerservice
            uri: lb://customerservice
            predicates:
              - Path=/api/v1/customer/**
          - id: catalogservice
            uri: lb://catalogservice
            predicates:
              - Path=/api/v1/product/**
              - Path=/api/v1/catalog/**
          
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
