spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: invoiceservice
  datasource:
    url: jdbc:postgresql://postgres:5432/tcellcrm
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true
